# Generated by Django 2.2 on 2021-05-05 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_ext',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
