# Generated by Django 2.2 on 2021-05-06 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210505_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='iban',
            field=models.CharField(blank=True, help_text='Please, enter your bank account number.', max_length=30, null=True),
        ),
    ]
