# Generated by Django 2.2 on 2021-05-07 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210506_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='iban',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
