# Generated by Django 2.2 on 2021-06-08 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210507_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='business',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
