# Generated by Django 2.2 on 2021-06-08 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210608_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_business',
        ),
    ]
