# Generated by Django 2.2 on 2021-06-08 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_customuser_is_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_business',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
