# Generated by Django 2.2 on 2021-06-09 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_customuser_is_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_business',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
