# Generated by Django 3.2.10 on 2021-12-29 06:51

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20211228_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
    ]
