# Generated by Django 3.2.10 on 2022-01-04 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20211229_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='user',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
