# Generated by Django 3.2.12 on 2022-02-22 23:06

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 5-15 characters allowed. Letters, digits and @/./+/-/_ only.', max_length=15, unique=True, validators=[users.models.MyValidator()], verbose_name='username'),
        ),
    ]
