# Generated by Django 3.2.13 on 2022-06-14 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_customuser_stripe_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='iso2',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
