# Generated by Django 3.2.14 on 2022-07-11 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_auto_20220709_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='business_website',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='iban',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='iso2',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='stripe_id',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='type_business',
        ),
        migrations.AddField(
            model_name='customuser',
            name='bank_account_number',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_ext',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='referral_code',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
