# Generated by Django 2.2 on 2021-04-16 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_balance', models.DecimalField(decimal_places=1, default=0, max_digits=10, null=True)),
                ('add_money', models.DecimalField(decimal_places=1, default=0, max_digits=10, null=True)),
                ('take_money', models.DecimalField(decimal_places=1, default=0, max_digits=10, null=True)),
                ('bonus', models.DecimalField(decimal_places=1, default=1000, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='account_interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.DecimalField(decimal_places=25, max_digits=40, null=True)),
                ('interest_rate', models.DecimalField(decimal_places=25, default=0, max_digits=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money_to_send', models.PositiveIntegerField(default=0, null=True)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
            ],
        ),
    ]
