# Generated by Django 2.2 on 2021-04-17 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210416_0251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_interest',
            name='interest',
            field=models.DecimalField(decimal_places=10, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='account_interest',
            name='interest_rate',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=30, null=True),
        ),
    ]
