# Generated by Django 2.2 on 2021-04-17 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210417_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_interest',
            name='interest',
            field=models.DecimalField(decimal_places=12, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='account_interest',
            name='interest_rate',
            field=models.DecimalField(decimal_places=12, default=0, max_digits=24, null=True),
        ),
    ]
