# Generated by Django 2.2 on 2021-04-25 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='add_money',
            field=models.DecimalField(decimal_places=1, help_text='deposit', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='take_money',
            field=models.DecimalField(decimal_places=1, help_text='withdraw', max_digits=10, null=True),
        ),
    ]
