# Generated by Django 2.2 on 2021-04-25 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210424_2131'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
        migrations.AlterField(
            model_name='account',
            name='add_money',
            field=models.DecimalField(decimal_places=1, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='take_money',
            field=models.DecimalField(decimal_places=1, max_digits=10, null=True),
        ),
    ]
