# Generated by Django 2.2 on 2021-04-25 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210424_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='add_money',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='take_money',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True),
        ),
    ]
