# Generated by Django 2.2 on 2021-05-01 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210424_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='target_account',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
