# Generated by Django 2.2 on 2021-05-03 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_transfer_target_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='money_to_send',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='target_account',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
