# Generated by Django 2.2 on 2021-05-03 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20210503_0107'),
    ]

    operations = [
        migrations.DeleteModel(
            name='transfer',
        ),
    ]
