# Generated by Django 2.2 on 2021-05-07 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_delete_transfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='target_account',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
