# Generated by Django 3.2.7 on 2021-12-19 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20210606_2123'),
    ]

    operations = [
        migrations.CreateModel(
            name='transaction_histoy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price', models.DecimalField(decimal_places=1, max_digits=10)),
                ('purpose_of_use', models.CharField(blank=True, max_length=500, null=True)),
                ('second_person', models.CharField(blank=True, max_length=50, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.account')),
            ],
        ),
    ]
