# Generated by Django 3.2.7 on 2021-12-19 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_transaction_histoy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction_histoy',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
