# Generated by Django 3.2.7 on 2021-12-19 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_transaction_histoy_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction_histoy',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='transaction_histoy',
            name='second_person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='second_person', to='accounts.account'),
        ),
    ]
