# Generated by Django 3.2.7 on 2021-12-19 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20211219_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction_histoy',
            name='second_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='second_person', to='accounts.account'),
        ),
    ]
