# Generated by Django 3.2.7 on 2021-12-19 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_transaction_histoy_second_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='transaction_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('price', models.DecimalField(decimal_places=1, max_digits=10)),
                ('purpose_of_use', models.CharField(blank=True, default='None', max_length=500, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.account')),
                ('second_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='second_person', to='accounts.account')),
            ],
        ),
        migrations.DeleteModel(
            name='transaction_histoy',
        ),
    ]
