# Generated by Django 3.2.10 on 2022-01-08 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_auto_20220104_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction_history',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='transaction_history',
            name='second_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_person', to='accounts.account'),
        ),
    ]
