# Generated by Django 3.2.10 on 2022-01-08 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_auto_20220107_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction_history',
            name='person',
            field=models.ForeignKey(blank=True, default='Anonymous', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='transaction_history',
            name='second_person',
            field=models.ForeignKey(blank=True, default='Anonymous', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_person', to='accounts.account'),
        ),
    ]
