# Generated by Django 3.2.11 on 2022-01-31 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_auto_20220113_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='bonus',
            field=models.DecimalField(decimal_places=1, max_digits=10, null=True),
        ),
    ]
