# Generated by Django 3.2.11 on 2022-02-01 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_alter_account_bonus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BranchAccounts',
        ),
    ]
