# Generated by Django 3.2.12 on 2022-02-20 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_auto_20220212_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction_history',
            name='purpose_of_use',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
