# Generated by Django 3.2.12 on 2022-02-20 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_auto_20220219_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction_history',
            name='ex_price',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='transaction_history',
            name='ex_rate',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10, null=True),
        ),
    ]
