# Generated by Django 3.2.12 on 2022-02-24 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_auto_20220219_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction_history',
            name='ex_rate',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='transaction_history',
            name='exchanged_price',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True),
        ),
    ]
