# Generated by Django 3.2.12 on 2022-02-24 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_auto_20220223_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction_history',
            name='ex_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='transaction_history',
            name='exchanged_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='transaction_history',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
