# Generated by Django 3.2.13 on 2022-06-13 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_auto_20220223_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='iso2',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
