# Generated by Django 3.2.13 on 2022-06-25 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_account_iso2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='account_interest',
            new_name='AccountInterest',
        ),
    ]
