# Generated by Django 3.2.13 on 2022-06-25 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_rename_account_interest_accountinterest'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='transaction_history',
            new_name='TransactionHistory',
        ),
    ]
