# Generated by Django 3.2.14 on 2022-07-10 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_alter_accountinterest_interest_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='main_currency',
            new_name='currency',
        ),
        migrations.RemoveField(
            model_name='account',
            name='money_to_send',
        ),
        migrations.RemoveField(
            model_name='account',
            name='target_account',
        ),
        migrations.AddField(
            model_name='account',
            name='primary',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='bonus',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True),
        ),
    ]
