# Generated by Django 3.2.14 on 2022-07-10 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_auto_20220709_2107'),
    ]

    operations = [
    ]
