# Generated by Django 3.2.14 on 2022-07-10 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0048_auto_20220709_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='bonus',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='currency',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
