# Generated by Django 3.2.14 on 2022-07-11 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0050_alter_account_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='add_money',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='take_money',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
