# Generated by Django 3.2.11 on 2022-02-01 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0034_delete_branchaccounts'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('add_money', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('take_money', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('currency', models.CharField(max_length=6, null=True)),
                ('main_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.account')),
            ],
        ),
    ]
