# Generated by Django 3.2.13 on 2022-06-13 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchaccounts',
            name='iso2',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
